# Anexo C: Construcción de sistemas de ecuaciones lineales implementados en Julia

## Paquetes

In [1]:
using LinearAlgebra

## Métodos

Implementación del método de Jacobi.

In [2]:
function SistEQ(tam::Int64, x::Array{Float64,1})
    
    #tam:= tamanio del sistema de EQ
    #x:= solucion del sistema
    
    #Matriz de coeficientes (A)
    A::Array{Float64,2} = diagm(1 => -ones(tam-1),
                                0 => 3*ones(tam),
                               -1 => -ones(tam-1))
    
    for i in 1:tam
        if A[i,tam-i+1] == 0.0 
            A[i,tam-i+1] = 0.5
        end
    end
    
    #Vector de constantes (b)
    b::Array{Float64,1} = A*x
    
    return A,b
end;

## Ejemplo: 

#### Tamaño de la entrada (tam)

In [3]:
tam = 5;

#### Matriz de coeficientes (A)

In [4]:
A,b = SistEQ(tam,ones(tam))
A

5×5 Array{Float64,2}:
  3.0  -1.0   0.0   0.0   0.5
 -1.0   3.0  -1.0   0.5   0.0
  0.0  -1.0   3.0  -1.0   0.0
  0.0   0.5  -1.0   3.0  -1.0
  0.5   0.0   0.0  -1.0   3.0

#### Vector de constantes (b)

In [5]:
b

5-element Array{Float64,1}:
 2.5
 1.5
 1.0
 1.5
 2.5

#### Tamaño de la entrada (tam)

In [6]:
tam = 6;

#### Matriz de coeficientes (A)

In [7]:
A,b = SistEQ(tam,ones(tam))
A

6×6 Array{Float64,2}:
  3.0  -1.0   0.0   0.0   0.0   0.5
 -1.0   3.0  -1.0   0.0   0.5   0.0
  0.0  -1.0   3.0  -1.0   0.0   0.0
  0.0   0.0  -1.0   3.0  -1.0   0.0
  0.0   0.5   0.0  -1.0   3.0  -1.0
  0.5   0.0   0.0   0.0  -1.0   3.0

#### Vector de constantes (b)

In [8]:
b

6-element Array{Float64,1}:
 2.5
 1.5
 1.0
 1.0
 1.5
 2.5

#### Tamaño de la entrada (tam)

In [9]:
tam = 10;

#### Matriz de coeficientes (A)

In [10]:
A,b = SistEQ(tam,ones(tam))
A

10×10 Array{Float64,2}:
  3.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.5
 -1.0   3.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.5   0.0
  0.0  -1.0   3.0  -1.0   0.0   0.0   0.0   0.5   0.0   0.0
  0.0   0.0  -1.0   3.0  -1.0   0.0   0.5   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   3.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   3.0  -1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.5   0.0  -1.0   3.0  -1.0   0.0   0.0
  0.0   0.0   0.5   0.0   0.0   0.0  -1.0   3.0  -1.0   0.0
  0.0   0.5   0.0   0.0   0.0   0.0   0.0  -1.0   3.0  -1.0
  0.5   0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   3.0

#### Vector de constantes (b)

In [11]:
b

10-element Array{Float64,1}:
 2.5
 1.5
 1.5
 1.5
 1.0
 1.0
 1.5
 1.5
 1.5
 2.5